name = "MonteCarlo"
uuid = "d36dbb3d-0fd2-44e3-8b1c-b03e82fd3171"
version = "1.0.0-DEV"
authors = ["AlexandrBatjanovsky <alexandersn@yandex.ru> and contributors"]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Molly = "aa0f7f06-fcc0-5ec4-a7f3-a573f33f9c4c"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CUDA = "=5.8.5"
Distributed = "1.11.0"
JuliaFormatter = "1.0.62"
LanguageServer = "4.1.0"
Molly = "0.23.0"
PythonCall = "0.9.31"
Revise = "3.13.0"
StaticArrays = "1.9.16"
Unitful = "1.27.0"
julia = "1.12"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
