name = "monte_carlo"
uuid = "d36dbb3d-0fd2-44e3-8b1c-b03e82fd3171"
authors = ["AlexandrBatjanovsky <alexandersn@yandex.ru> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
